<a href="https://colab.research.google.com/github/snitraM4500/AI_Course_Comprehensive_exercises/blob/main/multiply_matrixes/multiply_matrixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



A=
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & 9
\end{bmatrix}
,
B=
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}



1.   First we need to get the shapes of the columns, which are A=3x3 a B=3x3. What defines if 2 matrixs can multiply is wether the number of columns of the first element multiplyng is the same has the number of rows of the second element, in this case it is indeed 3x3 with 3x3 so it abides by that rule
2.   We multiply and add the elements of coumn 0 with the elements of row 0 and the result forms a new matrix.
3.  The resulting matrix will always be the number of rows of the first matrix with the number of columns of the second matrix. So the ending marix will be 3x3.

Below are the results that will compromise the new matrix
-----

---
0x0= -1 x 0 + 2 x 0 + 3 x 2 = 0 + 0 + 6 = 6

0x1= -1 x 2 + 2 x 2 + 3 x 9 = -2 + 4 + 27 = 29

0x2= -1 x 1 + 2 x -8 + 3 x -1 = -1 + -16 + -3 = -20

1x0 = 4 x 0 + -5 x 0 + 6 x 2 = 0 + 0 + 12 = 12

1x1 = 4 x 2 + -5 x 2 + 6 x 9 = 8 + -10 + 54 = 52

1x2 = 4 x 1 + -5 x -8 + 6 x -1 = 4 + 40 + -6 = 38

2x0 = 7 x 0 + 8 x 0 + 9 x 2 = 0 + 0 + 18 = 18

2x1 = 7 x 2 + 8 x 2 + 9 x 9 = 14 + 16 + 81 = 111

2x2 = 7 x 1 + 8 x -8 + 9 x -1 = 7 + -64 + -9 = -66

Therefore, the resulting matrix C = A x B is:

C = \begin{bmatrix} 6 & 29 & -20\\ 12 & 52 & 38\\
18 & 111 & -66 \end{bmatrix}



In [8]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [9]:
def multiply_matrixes(a_ndarray,b_ndarray):
  arows,acolumns=a_ndarray.shape
  brows,bcolumns=b_ndarray.shape
  if(acolumns==brows):
    new_array=np.zeros((arows,bcolumns))

    for i in range(arows):
      for j in range(bcolumns):
        for k in range(acolumns):
          new_array[i][j]+=a_ndarray[i][k]*b_ndarray[k][j]
  else:
    a_ndarray=np.transpose(a_ndarray)
    arows,acolumns=a_ndarray.shape
    if(acolumns==brows):
      print("Error ocurred when multiplying matrixes")
      print("Matrixes will be transposed to conttinue the product")
      new_array=np.zeros((arows,bcolumns))
      for i in range(arows):
        for j in range(bcolumns):
          for k in range(acolumns):
            new_array[i][j]+=a_ndarray[i][k]*b_ndarray[k][j]
    else:
        return ("These matrixes cannot be multiplied")
  return new_array

print(multiply_matrixes(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [10]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(multiply_matrixes(d_ndarray,e_ndarray))

Error ocurred when multiplying matrixes
Matrixes will be transposed to conttinue the product
[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]


In [13]:
p_ndarray = np.array([[-1, 2],[3,6]])
v_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(multiply_matrixes(p_ndarray,v_ndarray))

[[ 21. -18.   1.]
 [  9.  -6.  45.]]


In [16]:
p_ndarray = np.array([[-1, 2],[3,6],[8,9]])
v_ndarray = np.array([ [8, 7], [ -5, 4],[7,3]])

print(multiply_matrixes(p_ndarray,v_ndarray))

Error ocurred when multiplying matrixes
Matrixes will be transposed to conttinue the product
[[33. 29.]
 [49. 65.]]
